# Generated by Django 5.0.6 on 2024-06-05 19:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=101)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora_creacio', models.TimeField()),
                ('preu_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_telefon', models.CharField(max_length=20)),
                ('adreca', models.CharField(max_length=255)),
                ('data_naix', models.DateField()),
                ('preferits', models.ManyToManyField(related_name='clients_preferits', to='la_burguesa.producte')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleat',
            fields=[
                ('dni', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('data_naix', models.DateField()),
                ('data_contractacio', models.DateField()),
                ('sou', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Acompanyament',
            fields=[
                ('producte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.producte')),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Beguda',
            fields=[
                ('producte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.producte')),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('producte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.producte')),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeRecollida',
            fields=[
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.comanda')),
                ('hora_recollida', models.TimeField()),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Confirmada', 'Confirmada'), ('En preparació', 'En preparació'), ('En camí', 'En camí'), ('Completada', 'Completada')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='username_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.client'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='dni_processada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.empleat'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat_prod', models.IntegerField()),
                ('preu_pagat_producte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.comanda')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.producte')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='valorats',
            field=models.ManyToManyField(through='la_burguesa.Item', to='la_burguesa.producte'),
        ),
        migrations.CreateModel(
            name='Propietat',
            fields=[
                ('numero_propietat', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat_propietat', models.IntegerField()),
                ('descartats', models.ManyToManyField(related_name='propietats_descartats', to='la_burguesa.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.item')),
                ('suplements', models.ManyToManyField(related_name='propietats_suplements', to='la_burguesa.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('comentari', models.TextField()),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.producte')),
                ('username_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='valorats',
            field=models.ManyToManyField(related_name='clients_valorats', through='la_burguesa.Valoracio', to='la_burguesa.producte'),
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('producte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.producte')),
                ('descripcio', models.TextField()),
                ('ingredients_conte', models.ManyToManyField(to='la_burguesa.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('producte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.producte')),
                ('suma_preus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acompanyament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.acompanyament')),
                ('beguda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.beguda')),
                ('hamburguesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.hamburguesa')),
                ('postre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.postre')),
            ],
        ),
        migrations.CreateModel(
            name='ADomicili',
            fields=[
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='la_burguesa.comanda')),
                ('hora_entrega', models.TimeField()),
                ('adreca_lliurament', models.CharField(max_length=255)),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Confirmada', 'Confirmada'), ('En preparació', 'En preparació'), ('Llesta per emportar', 'Llesta per emportar'), ('Completada', 'Completada')], max_length=100)),
                ('dni_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_burguesa.empleat')),
            ],
        ),
    ]
